// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Fatih Rizqon",
            "email": "fatihrizqon@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/akun": {
            "get": {
                "description": "Retrieve all akun records with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Akun"
                ],
                "summary": "Get all akun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all records.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Store a new akun record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Akun"
                ],
                "summary": "Create akun",
                "parameters": [
                    {
                        "description": "Akun Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AkunCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A new record has been stored.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/akun/{id}": {
            "get": {
                "description": "Retrieve a single akun by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Akun"
                ],
                "summary": "Get akun by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Akun ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved selected record.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "Akun not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Update akun data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Akun"
                ],
                "summary": "Update akun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Akun ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Akun Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AkunUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been updated.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "Akun not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a akun record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Akun"
                ],
                "summary": "Delete akun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Akun ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been deleted.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "Akun not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/akun_grup": {
            "get": {
                "description": "Retrieve all akun_grup records with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunGrup"
                ],
                "summary": "Get all akun_grup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all records.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Store a new akun_grup record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunGrup"
                ],
                "summary": "Create akun_grup",
                "parameters": [
                    {
                        "description": "AkunGrup Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AkunGrupCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A new record has been stored.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/akun_grup/{id}": {
            "get": {
                "description": "Retrieve a single akun_grup by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunGrup"
                ],
                "summary": "Get akun_grup by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AkunGrup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved selected record.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "AkunGrup not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Update akun_grup data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunGrup"
                ],
                "summary": "Update akun_grup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AkunGrup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AkunGrup Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AkunGrupUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been updated.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "AkunGrup not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a akun_grup record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunGrup"
                ],
                "summary": "Delete akun_grup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AkunGrup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been deleted.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "AkunGrup not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/akun_subgrup": {
            "get": {
                "description": "Retrieve all akun_subgrup records with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunSubgrup"
                ],
                "summary": "Get all akun_subgrup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all records.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Store a new akun_subgrup record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunSubgrup"
                ],
                "summary": "Create akun_subgrup",
                "parameters": [
                    {
                        "description": "AkunSubgrup Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AkunSubgrupCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A new record has been stored.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/akun_subgrup/{id}": {
            "get": {
                "description": "Retrieve a single akun_subgrup by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunSubgrup"
                ],
                "summary": "Get akun_subgrup by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AkunSubgrup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved selected record.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "AkunSubgrup not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Update akun_subgrup data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunSubgrup"
                ],
                "summary": "Update akun_subgrup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AkunSubgrup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AkunSubgrup Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AkunSubgrupUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been updated.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "AkunSubgrup not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a akun_subgrup record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AkunSubgrup"
                ],
                "summary": "Delete akun_subgrup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AkunSubgrup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been deleted.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "AkunSubgrup not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate user and return a JWT token in a cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AuthJSON"
                        }
                    },
                    "400": {
                        "description": "Invalid request format",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Logout user dengan menghapus access_token dan refresh_token dari cookie,\nserta memasukkan refresh token ke blacklist.",
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "Successfully logged out",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "description": "Retrieve the current authenticated user's information using the access token stored in HttpOnly cookie or Authorization header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get authenticated user info",
                "responses": {
                    "200": {
                        "description": "User info retrieved",
                        "schema": {
                            "$ref": "#/definitions/response.AuthJSON"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing access token",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh the access token using the refresh token from HttpOnly cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "Access token refreshed",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Invalid request format",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing refresh token",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/jurnal": {
            "get": {
                "description": "Retrieve all jurnal records with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jurnal"
                ],
                "summary": "Get all jurnal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all records.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Store a new jurnal record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jurnal"
                ],
                "summary": "Create jurnal",
                "parameters": [
                    {
                        "description": "Jurnal Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JurnalCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A new record has been stored.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/jurnal/{id}": {
            "get": {
                "description": "Retrieve a single jurnal by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jurnal"
                ],
                "summary": "Get jurnal by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jurnal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved selected record.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "Jurnal not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Update jurnal data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jurnal"
                ],
                "summary": "Update jurnal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jurnal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Jurnal Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JurnalUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been updated.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "Jurnal not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a jurnal record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jurnal"
                ],
                "summary": "Delete jurnal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jurnal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been deleted.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "Jurnal not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/jurnal_tipe": {
            "get": {
                "description": "Retrieve all jurnal_tipe records with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JurnalTipe"
                ],
                "summary": "Get all jurnal_tipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all records.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Store a new jurnal_tipe record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JurnalTipe"
                ],
                "summary": "Create jurnal_tipe",
                "parameters": [
                    {
                        "description": "JurnalTipe Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JurnalTipeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A new record has been stored.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/jurnal_tipe/{id}": {
            "get": {
                "description": "Retrieve a single jurnal_tipe by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JurnalTipe"
                ],
                "summary": "Get jurnal_tipe by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JurnalTipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved selected record.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "JurnalTipe not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Update jurnal_tipe data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JurnalTipe"
                ],
                "summary": "Update jurnal_tipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JurnalTipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JurnalTipe Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JurnalTipeUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been updated.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "JurnalTipe not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a jurnal_tipe record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JurnalTipe"
                ],
                "summary": "Delete jurnal_tipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JurnalTipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been deleted.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "JurnalTipe not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "Retrieve all user records with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all records.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Store a new user record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A new record has been stored.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "description": "Retrieve a single user by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved selected record.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Update user data by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been updated.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a user record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Selected record has been deleted.",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSON"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.AkunCreateRequest": {
            "type": "object",
            "required": [
                "id_akun_subgrup",
                "jenis",
                "kode",
                "nama"
            ],
            "properties": {
                "id_akun": {
                    "type": "string"
                },
                "id_akun_subgrup": {
                    "type": "string"
                },
                "jenis": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "nama": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "saldo_awal": {
                    "type": "number"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "request.AkunGrupCreateRequest": {
            "type": "object",
            "required": [
                "kode",
                "nama"
            ],
            "properties": {
                "kode": {
                    "type": "string",
                    "maxLength": 12
                },
                "nama": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "request.AkunGrupUpdateRequest": {
            "type": "object",
            "required": [
                "kode",
                "nama"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "kode": {
                    "type": "string",
                    "maxLength": 12
                },
                "nama": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "request.AkunSubgrupCreateRequest": {
            "type": "object",
            "required": [
                "id_akun_grup",
                "kode",
                "nama"
            ],
            "properties": {
                "id_akun_grup": {
                    "type": "string"
                },
                "kode": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "nama": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "request.AkunSubgrupUpdateRequest": {
            "type": "object",
            "required": [
                "id_akun_grup",
                "kode",
                "nama"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "id_akun_grup": {
                    "type": "string"
                },
                "kode": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "nama": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "request.AkunUpdateRequest": {
            "type": "object",
            "required": [
                "id_akun_subgrup",
                "jenis",
                "kode",
                "nama"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "id_akun": {
                    "type": "string"
                },
                "id_akun_subgrup": {
                    "type": "string"
                },
                "jenis": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "nama": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "saldo_awal": {
                    "type": "number"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "request.JurnalCreateRequest": {
            "type": "object",
            "required": [
                "id_jurnal_tipe",
                "jurnal_detail",
                "keterangan"
            ],
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "id_jurnal_tipe": {
                    "type": "string"
                },
                "jurnal_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.JurnalDetailCreateRequest"
                    }
                },
                "keterangan": {
                    "type": "string"
                },
                "nota": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                }
            }
        },
        "request.JurnalDetailCreateRequest": {
            "type": "object",
            "required": [
                "id_akun",
                "id_jurnal",
                "jenis",
                "nominal"
            ],
            "properties": {
                "id_akun": {
                    "type": "string"
                },
                "id_jurnal": {
                    "type": "string"
                },
                "jenis": {
                    "type": "integer"
                },
                "nominal": {
                    "type": "number"
                }
            }
        },
        "request.JurnalDetailUpdateRequest": {
            "type": "object",
            "required": [
                "id_akun",
                "id_jurnal",
                "jenis",
                "nominal"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "id_akun": {
                    "type": "string"
                },
                "id_jurnal": {
                    "type": "string"
                },
                "jenis": {
                    "type": "integer"
                },
                "nominal": {
                    "type": "number"
                }
            }
        },
        "request.JurnalTipeCreateRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "request.JurnalTipeUpdateRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "request.JurnalUpdateRequest": {
            "type": "object",
            "required": [
                "id_jurnal_tipe",
                "jurnal_detail",
                "keterangan"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "id_jurnal_tipe": {
                    "type": "string"
                },
                "jurnal_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.JurnalDetailUpdateRequest"
                    }
                },
                "keterangan": {
                    "type": "string"
                },
                "nota": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1,
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "yoursecretpassword"
                }
            }
        },
        "request.UserCreateRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                }
            }
        },
        "request.UserUpdateRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "minLength": 1
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 1
                }
            }
        },
        "response.AuthJSON": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/response.UserInfo"
                }
            }
        },
        "response.JSON": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {},
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/response.Meta"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Links": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "string"
                },
                "first_page": {
                    "type": "string"
                },
                "last_page": {
                    "type": "string"
                },
                "next_page": {
                    "type": "string"
                },
                "prev_page": {
                    "type": "string"
                }
            }
        },
        "response.Meta": {
            "type": "object",
            "properties": {
                "info": {
                    "type": "string"
                },
                "links": {
                    "$ref": "#/definitions/response.Links"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "response.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go REST API with Fiber Framework",
	Description:      "This is an Official Documentation for Go REST API with Fiber Framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
